// tag::FEEDBACK[]
:filename: 01-basics/05-curriculum-outline.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::EN[]
=== Structure of the curriculum

The sections of the curriculum are laid out as follows:

- **Terms/concepts**: core terminology of the topic
- **Instruction/exercise time**: specifies the minimum durations for instruction and exercise blocks for licensed trainings
- **Learning goals**: describes in detail the lessons, including core terminology and concepts

This section outlines the knowledge to be gained in the training sessions.
The learning goals are classified according to the following categories:

- What should the participants **be able to do**? Participants should be able to apply these concepts by themselves without guidance. In courses, these topics should be covered by exercises and are part of the examination {curriculum-short} and/or the final examination of the iSAQB Advanced Level.
- What should the participants **understand**? These topics may be part of the examination {curriulum-short}.
- What should the participants **know**? These topics (terminology, concepts, methods, practices) may aid understanding or motivate broader concepts. They are not part of the examination and may be discussed in trainings on a basic, abstract level.
// end::EN[]
