= https://isaqb.org[iSAQB] Advanced Level Curriculum BLOCKCHAIN

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-blockchain/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-blockchain/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-blockchain.svg["Contributors",link="https://github.com/isaqb-org/curriculum-blockchain/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-blockchain.svg["Issues",link="https://github.com/isaqb-org/curriculum-blockchain/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-blockchain.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-blockchain/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the iSAQB Advanced Level curriculum BLOCKCHAIN in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to build the documents

Prerequisite: You need a Java Runtime(tm) installed.

You build the output documents with gradle.
That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.

In case you want to change that, adjust the following part of `build.gradle`:

[source,groovy]
----
task buildDocs {
  group 'Documentation'
  description 'Grouping task for generating all languages in several formats'
  dependsOn "includeLearningObjectives", "renderDE", "renderEN"
}
----

In the task "renderDE", certain attributes (aka variables) are defined that configure the corresponding output.

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Lars Hupel.
It is based on https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
